application:
  subdomain: hermes
  upstreams:
    - location: /
      backend: http://hermes-webui:{{ .U.port }}/
    - location: /preview/
      backend: http://hermes-webui:{{ .U.preview_frontend_port }}/
    - location: /xai-oauth/
      backend: http://hermes-webui:{{ .U.xai_oauth_port }}/
  public_path:
    - /

services:
  hermes-webui:
    #  ekkoye8888/hermes-web-ui:v0.6.14
    image: registry.lazycat.cloud/czyt/ekkoye8888/hermes-web-ui:b476fb4cbd119a38
    environment:
      - PORT={{ .U.port }}
      - HERMES_HOME=/home/agent/.hermes
      - HERMES_BIN=/opt/hermes/.venv/bin/hermes
      - HERMES_WEB_UI_MANAGED_GATEWAY=1
      - HERMES_WEB_UI_XAI_CALLBACK_BIND_HOST=0.0.0.0
      - PATH=/opt/hermes/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HERMES_ALLOW_ROOT_GATEWAY=1
    binds:
      - /lzcapp/var/hermes:/home/agent/.hermes
      - /lzcapp/var/hermes-web-ui:/home/agent/.hermes-web-ui
